FROM ray-example-base
ADD launch_job.sh /app/launch_job.sh
ADD plot_pong_example.ipynb /app/plot_pong_example.ipynb
ADD plot_pong_example.py /app/plot_pong_example.py
ENTRYPOINT [ "sh", "/app/launch_job.sh"]