FROM python:3.8.10

RUN pip install dm-tree dm-reverb[tensorflow] ray
RUN pip install tensorflow_probability
RUN pip install ray[default]==1.3
RUN apt update && apt install -y cmake
ADD requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
RUN pip install gym[atari]==0.18.0
